apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexporter
  namespace: argocd
  labels:
    app: monitoring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: monitoring/prometheus-node-exporter
    repoURL: 'https://github.com/gru6er/argo'
    targetRevision: main
    helm:
      valueFiles:
        - my-values.yaml
  project:  monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
