ingress:
  enabled: true
  # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
  # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
  ingressClassName: nginx
  # Values can be templated
  annotations: 
    cert-manager.io/issuer: "monitoring-issuer"
    kubernetes.io/ingress.class: nginx
  labels: {}
  path: /

  # pathType is only for k8s >= 1.1=
  pathType: Prefix

  hosts:
    - grafana.zgz.local
  ## Extra paths to prepend to every host configuration. This is useful when working with annotation based services.
  extraPaths: []
  # - path: /*
  #   backend:
  #     serviceName: ssl-redirect
  #     servicePort: use-annotation
  ## Or for k8s > 1.19
  # - path: /*
  #   pathType: Prefix
  #   backend:
  #     service:
  #       name: ssl-redirect
  #       port:
  #         name: use-annotation


  tls: 
   - secretName: grafana-tls
     hosts:
       - grafana.zgz.local


revisionHistoryLimit: 3
testFramework:
  enabled: false
resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi
persistence:
  type: pvc
  enabled: true
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  size: 2Gi
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Victoria
      type: prometheus
      url: http://victoriametrics-victoria-metrics-single-server:8428
      access: proxy
      isDefault: true
