
replicaCount: 1

# Настройки образа
image:
  repository: victoriametrics/vmagent
  tag: "v1.112.0"
  pullPolicy: IfNotPresent

# Переопределение имен
nameOverride: "vmagent-sys"
fullnameOverride: "vmagent-sys"

# Настройки remoteWrite
remoteWrite:
  - url: "http://victoriametrics-victoria-metrics-single-server:8428/api/v1/write"
    # Дополнительные настройки (необязательно):
    # remoteTimeout: "30s"
    # writeRelabelConfigs: []

# Настройки сервиса
service:
  enabled: true
  port: 8429
  type: ClusterIP

# Настройки Ingress
ingress:
  # -- Enable deployment of ingress for agent
  enabled: true
  
  # -- Ingress annotations
  annotations: 
    cert-manager.io/issuer: "monitoring-issuer"
  #   kubernetes.io/ingress.class: nginx
  #   kubernetes.io/tls-acme: 'true'

  # -- Ingress extra labels
  extraLabels: {}
  
  # -- Array of host objects
  hosts:
    - name: vmagent.zgz.local
      path:
        - / 
      port: http
  
  # -- Array of TLS objects
  tls:
    - secretName: "vmagent-tls"
      hosts:
        - vmagent.zgz.local

  # -- Ingress controller class name
  ingressClassName: "nginx"

  # -- Ingress path type
  pathType: Prefix



# Ресурсы
resources:
  requests:
    cpu: 200m
    memory: 200Mi
  limits:
    cpu: 500m
    memory: 600Mi

# Настройки Persistent Volume
persistence:
  enabled: true
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  size: 2Gi

# Конфигурация scrape
config:
  global:
    scrape_interval: 10s

# Дополнительные конфигурации для скрейпа
extraScrapeConfigs:
  - job_name: 'node-exporter'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_endpoints_name]
        regex: 'nexporter-prometheus-node-exporter'
        action: keep
  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['ksm-kube-state-metrics.monitoring.svc.cluster.local:8080']
  - job_name: 'nginx-ingress'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - default # namespace where your ingress is deployed
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        action: keep
        regex: nginx-ingress
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: replace
        regex: (.+);true
        replacement: ${1}:10254
        target_label: __address__
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_name