apiVersion: v2
name: alertmanager
description: Alertmanager
type: application
version: 1.15.1
appVersion: v0.28.0
dependencies:
  - name: alertmanager
    version: 1.15.1
    repository: https://prometheus-community.github.io/helm-charts
