alertmanager:
  nameOverride: "alertmanager"
  fullnameOverride: "alertmanager"
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/issuer: "monitoring-issuer"
    hosts:
      - host: am.zgz.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - am.zgz.local
        secretName: am-tls
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 32Mi
  persistence:
    enabled: true
    storageClass: "nfs"
    accessModes:
      - ReadWriteOnce
    size: 50Mi
  config:
    global:
      resolve_timeout: 5m
    receivers:
      - name: 'telegram'
        telegram_configs:
        - bot_token: '7711735369:AAEWcawN8rV1Py2LkeBqHq091bhpKQyy38c' # Замените your-bot-token на ваш токен бота
          chat_id: '1348935100'
    route:
      group_by: ['...']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'telegram'