{
 "title": "Main dashboard",
 "tags": [
  "1-st line",
  "art-dashboards"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": { "query": "kube_namespace_created" } },
   { "name": "node", "query": { "query": "kube_node_info" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "---\n* [Список серверов](/d/art-nodes)\n  * [Подробная информация о сервере](/d/art-node-exporter)\n* [Кластер k8s](/d/art-k8s)\n  * [Список подов кластера](/d/art-k8s-list-of-pods)\n  * [Подробная информация по подам](/d/art-k8s-pod-info)\n* [Victoriametrics](/d/art-victoria)\n* [Ingress nginx controller](/d/art-ingress-nginx)\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Containers Restarts (Last 30 min)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total[30m]))"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Memory Requested by Containers",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node=~\"$node\", namespace=~\"$namespace\"})",
     "legendFormat": "Requets"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", node=~\"$node\", namespace=~\"$namespace\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\",node=~\"$node\"})",
     "legendFormat": "Allocatable"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", node=~\"$node\",resource=\"cpu\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", node=~\"$node\",resource=\"cpu\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\",node=~\"$node\"})",
     "legendFormat": "Allocatable"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count by(instance)(node_cpu_seconds_total{job=\"$job\",mode=\"idle\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "node_uname_info{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "1 - avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\",job=\"$job\"}[5m]))"
    },
    {
     "expr": "(sum by(instance)(node_load5{job=\"$job\"}) * 100) / count by(instance)(node_cpu_seconds_total{job=\"$job\",  mode=\"idle\"})"
    },
    {
     "expr": "(sum by(instance)(node_load15{job=\"$job\"}) * 100) / count by(instance)(node_cpu_seconds_total{job=\"$job\",  mode=\"idle\"})"
    },
    {
     "expr": "100 - (sum by(instance)(node_memory_MemAvailable_bytes{job=\"$job\"}) * 100) /\nsum by(instance)(node_memory_MemTotal_bytes{job=\"$job\"})"
    },
    {
     "expr": "100 - ((sum by(instance)(node_filesystem_avail_bytes{job=\"$job\",mountpoint=\"/\"}) * 100) \n/ sum by(instance)(node_filesystem_size_bytes{job=\"$job\", mountpoint=\"/\"}))"
    },
    {
     "expr": "100 - \n((sum by(instance)(node_filesystem_avail_bytes{job=\"$job\",mountpoint=\"/mnt/dc5_d33_npu_nfs_01\"}) * 100) \n/ sum by(instance)(node_filesystem_size_bytes{job=\"$job\",mountpoint=\"/mnt/dc5_d33_npu_nfs_01\"}))"
    },
    {
     "expr": "sum by(instance)(node_memory_MemTotal_bytes{job=\"$job\"})"
    }
   ]
  }
 ]
}