victoria-metrics-single:
  rbac:
    create: false
    pspEnabled: false
  serviceAccount:
    create: false
  server:
    retentionPeriod: 6h
    extraArgs:
      selfScrapeInterval: "15s"
      loggerLevel: "INFO"
    persistentVolume:
      storageClass: "nfs"
      size: "10Gi"
    resources:
      requests:
        cpu: 200m
        memory: 500Mi
      limits:
        cpu: "1"
        memory: 2Gi
    ingress:
      enabled: true
      annotations:
        cert-manager.io/issuer: "monitoring-issuer"
      hosts:
        - name: "vm.zgz.local"
          path: /
          port: 9090
      tls:
        - secretName: "mon-tls"
          hosts:
            - vm.zgz.local
      ingressClassName: system-ingress
    statefulSet:
      enabled: true
      podManagementPolicy: Parallel
    scrape:
      enabled: false

