victoria-metrics-alert:
  server:
    image:
      tag: "v1.112.0"
    nameOverride: "vmalert"
    fullnameOverride: "vmalert"
    datasource:
      url: "http://victoriametrics-victoria-metrics-single-server:8428"
    notifier:
      alertmanager:
        url: "http://alertmanager:9093"
    ingress:
    # -- Enable deployment of ingress for vmalert component
      enabled: true

      # -- Ingress annotations
      annotations:
          cert-manager.io/issuer: "monitoring-issuer"
      #   kubernetes.io/ingress.class: nginx
      #   kubernetes.io/tls-acme: 'true'

      # -- Ingress extra labels
      extraLabels: {}

      # -- Array of host objects
      hosts:
        - name: vmalert.zgz.local
          path:
            - /
          port: http

      # -- Array of TLS objects
      tls: 
        - secretName: vmalert-tls
          hosts:
            - vmalert.zgz.local

      # -- Ingress controller class name
      ingressClassName: "nginx"

      # -- Ingress path type
      pathType: Prefix
    
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    priorityClassName: "low-priority"
    # Тут будем добавлять алёрты
    config:
      alerts:
        groups:
          - name: node resources
            rules:
              - alert: NodeCpuUsage
                expr: (100 - avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) without (cpu) * 100) * on(instance,job) group_left(nodename) node_uname_info > 95
                for: 5m
                labels:
                  severity: warning
                annotations:
                  description: "Средняя загрузка процессора"
                  summary: "Средняя загрузка процессора по ядрам на (instance {{ $labels.nodename }}) превышает допустимые значения. \n\n Текущее значение: {{ humanize $value }}%."
              - alert: NodeOutOfMemory
                expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100) * on(instance,job) group_left(nodename) node_uname_info < 5
                for: 1m
                labels:
                  severity: critical
                annotations:
                  description: "Свободной физической памяти осталось: {{ humanize $value }} %"
                  summary: "Использование оперативной памяти на {{ $labels.nodename }} превышает допустимые значения."    
              - alert: NodeCriticalSystemUptime
                expr: (time() - node_boot_time_seconds) * on(instance,job) group_left(nodename) node_uname_info < 600
                for: 1m
                labels:
                  severity: critical
                annotations:
                  summary: "Зафиксирована перезагрузка сервера. Текущий uptime: {{ humanize $value }} секунд."
                  description: "Система: {{ $labels.group }} \n Хост: {{ $labels.nodename }} \n Приоритет: {{ $labels.severity }} "                    
          - name: kube-pods
            rules:
              - alert: ZeroDeploymentPods
                expr: kube_deployment_status_replicas_available == 0
                for: 1m
                labels:
                  severity: critical
                annotations:
                  description: "Количество подов равно 0!"
                  summary: "Количество подов деплоймента {{ $labels.deployment }} в namespace {{ $labels.namespace }} равно нулю!"
              #    dashboard: "https://grafana.zgz.local/d/art-pods-alerts/alarm-list"
              - alert: ZeroStatefulSetPods
                expr: kube_statefulset_status_replicas_current == 0
                for: 1m
                labels:
                  severity: critical
                annotations:
                  description: "Количество подов равно 0!"
                  summary: "Количество подов StatefullSet {{ $labels.statefulset }} в namespace {{ $labels.namespace }} равно нулю!"
                  dashboard: "https://grafana.kryukov.local/d/art-pods-alerts/alarm-list?orgId=1"

              - alert: ZeroDaemonSetPods
                expr: kube_daemonset_status_number_available == 0
                for: 1m
                labels:
                  severity: critical
                annotations:
                  description: "Количество подов равно 0!"
                  summary: "Количество подов DaemonSet {{ $labels.daemonset }} в namespace {{ $labels.namespace }} равно нулю!"
                  dashboard: "https://grafana.kryukov.local/d/art-pods-alerts/alarm-list?orgId=1"

              - alert: ToManyContainerRestarts
                expr: increase(kube_pod_container_status_restarts_total[1m]) > 3
                for: 2m
                labels:
                  severity: warning
                annotations:
                  description: "Контейнер слишком часто рестартует!"
                  summary: "Контейнер {{ $labels.container }} пода {{ $labels.pod }} в namespace {{ $labels.namespace }} слишком
                            часто рестартует."
                  dashboard: "https://grafana.kryukov.local/d/art-k8s/kubernetes-cluster?orgId=1&viewPanel=41&var-datasource=Victoria&var-node=All&var-namespace={{ $labels.namespace }}"
                  container: "https://grafana.kryukov.local/d/art-k8s-pod-info/k8s-pod?&orgId=1&var-ds=Victoriavar-pod={{ $labels.pod }}&var-namespace={{ $labels.namespace }}&var-container={{ $labels.container }}"

              - alert: PodPendingToLong
                expr: kube_pod_status_phase{phase="Pending"} > 0
                for: 10m
                labels:
                  severity: warning
                annotations:
                  description: "Pod слишком долго не запускается!"
                  summary: "Под {{ $labels.pod }} в namespace {{ $labels.namespace }} слишком долго не запускается."
                  dashboard: "https://grafana.kryukov.local/d/art-k8s/kubernetes-cluster?orgId=1&viewPanel=31&var-datasource=Victoria&var-node=All&{{ $labels.namespace }}"
                  container: "https://grafana.kryukov.local/d/art-k8s-pod-info/k8s-pod?&orgId=1&var-ds=Victoriavar-pod={{ $labels.pod }}&var-namespace={{ $labels.namespace }}"
