victoria-metrics-alert:
  server:
    image:
      tag: "v1.112.0"
    nameOverride: "vmalert"
    fullnameOverride: "vmalert"
    datasource:
      url: "http://victoriametrics-victoria-metrics-single-server:8428"
    notifier:
      alertmanager:
        url: "http://alertmanager:9093"
    ingress:
    # -- Enable deployment of ingress for vmalert component
    enabled: true

    # -- Ingress annotations
    annotations:
        cert-manager.io/issuer: "monitoring-issuer"
    #   kubernetes.io/ingress.class: nginx
    #   kubernetes.io/tls-acme: 'true'

    # -- Ingress extra labels
    extraLabels: {}

    # -- Array of host objects
    hosts:
      - name: vmalert.zgz.local
        path:
          - /
        port: http

    # -- Array of TLS objects
    tls: 
      - secretName: vmalert-tls
        hosts:
          - vmalert.zgz.local

    # -- Ingress controller class name
    ingressClassName: "nginx"

    # -- Ingress path type
    pathType: Prefix
    
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    priorityClassName: "low-priority"
    # Тут будем добавлять алёрты
    config:
      alerts:
        groups:
          - name: resources-cpu
            rules:
              - alert: NodeCpuUsage
                expr: 100 - avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) without (cpu) * 100 > 85
                for: 5m
                labels:
                  severity: warning
                annotations:
                  description: "Средняя загрузка процессора по ядрам на (instance {{ $labels.lhostname }}) превышает допустимые значения. \n\n Текущее значение: {{ humanize $value }}%."
                  summary: "Дополнительная информация: \n "